name: Push latest component

on:
  push:
    branches:
      - master

env:
  DOCKER_REPO: davidthor/mailslurper

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download arcctl
        run: curl -sSL https://arcctl-backend.nyc3.digitaloceanspaces.com/arcctl --output arcctl && chmod +x ./arcctl
      - name: Build latest component
        run: ./arcctl build . -t ${{ env.DOCKER_REPO }}:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push latest component
        run: ./arcctl push ${{ env.DOCKER_REPO }}:latest